version: "3.1"
services:
  php-fpm:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todocake-webserver
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app/webroot
    ports:
      - "80:80"
      - "8765:8765"
    entrypoint: ["/entrypoint.sh"]
  mysql:
    image: mysql:5.6
    container_name: todocake-mysql
    volumes:
      - ./tmp/data/mysql_db:/var/lib/mysql
    env_file:
      - mysql.env
    command: mysqld --character-set-server=utf8 --init-connect='SET NAMES UTF8;'
    ports:
      - "3306:3306"

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - '8080:80'
  #   volumes:
  #     - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
  #   depends_on:
  #     - php-fpm
